import os
import numpy as np
import librosa
import main as eg
 
OUT = os.path.join("firmware", "esp_features", "mel_filters.h")

def main():
    n_fft = int(eg.sample_rate * eg.frame_length / 1000)
    hop = int(eg.sample_rate * eg.hop_length / 1000)
  
    M = librosa.filters.mel(sr=eg.sample_rate, n_fft=n_fft, n_mels=eg.num_mel)
 
    starts, lens, offsets, weights = [], [], [], []
    for b, row in enumerate(M):
        nz = np.nonzero(row)[0]
        if len(nz) == 0:
            raise SystemExit(f"band {b} is empty: too many mel bands for this FFT size")
        lo, hi = int(nz[0]), int(nz[-1]) + 1
        starts.append(lo)
        lens.append(hi - lo)
        offsets.append(len(weights))
        weights.extend(np.float32(w) for w in row[lo:hi])
 
    def c_list(values, fmt):
        items = [fmt(v) for v in values]
        lines = [", ".join(items[i:i + 8]) for i in range(0, len(items), 8)]
        return "{\n  " + ",\n  ".join(lines) + "\n}"
 
    header = f"""// Generated by export_mel.py from librosa.filters.mel. Do not edit by hand:
// re-run export_mel.py if the audio settings in main.py change.
#pragma once
#include <stdint.h>
 
#define EG_SAMPLE_RATE {eg.sample_rate}
#define EG_N_FFT       {n_fft}
#define EG_HOP         {hop}
#define EG_N_MELS      {eg.num_mel}
 
// Band m uses FFT bins MEL_START[m] .. MEL_START[m] + MEL_LEN[m] - 1,
// with weights starting at MEL_WEIGHTS[MEL_OFFSET[m]].
static const uint16_t MEL_START[EG_N_MELS]  = {c_list(starts, str)};
static const uint16_t MEL_LEN[EG_N_MELS]    = {c_list(lens, str)};
static const uint16_t MEL_OFFSET[EG_N_MELS] = {c_list(offsets, str)};
static const float    MEL_WEIGHTS[{len(weights)}] = {c_list(weights, lambda w: f"{w:.9g}f")};
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(header)
    print(f"wrote {OUT}: {eg.num_mel} bands, {len(weights)} weights, "
          f"n_fft={n_fft}, hop={hop}")
 
 
if __name__ == "__main__":
    main()
