import argparse
import os
import zlib
import numpy as np
import main as eg
import export_mel

FW_DIR = os.path.join("firmware", "esp_detector")


def model_id(arrays):
    """A fingerprint of the trained detector. The firmware reports it in every
    packet, so the laptop can tell which detector the chip is running."""
    crc = 0
    for a in arrays:
        crc = zlib.crc32(np.ascontiguousarray(a, dtype="<f4").tobytes(), crc)
    return crc & 0xFFFFFFFF


def c_array(ctype, name, values, fmt, per_line=8):
    items = [fmt(v) for v in values]
    lines = [", ".join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
    return (f"static const {ctype} {name}[{len(items)}] = {{\n  "
            + ",\n  ".join(lines) + "\n};\n")


def f32(v):
    return f"{np.float32(v):.9g}f"


def main():
    ap = argparse.ArgumentParser(description="Train the detector and export it for the ESP32")
    ap.add_argument("--healthy", default="recordings/healthy.wav",
                    help="healthy recording to learn from")
    args = ap.parse_args()

    print(f"training on {args.healthy} ...")
    det = eg.Detector()
    det.fit(eg.extract_features(args.healthy))

    n_res, n_in = det.W_in.shape
    n_ext = 1 + n_in + n_res                  
  
    row_start, cols, vals = [0], [], []
    for i in range(n_res):
        nz = np.nonzero(det.W[i])[0]
        cols.extend(int(c) for c in nz)
        vals.extend(det.W[i, nz])
        row_start.append(len(cols))
    col_type = "uint8_t" if n_res <= 256 else "uint16_t"

    w_out_t = det.W_out.T                     

    mid = model_id([det.mu, det.sig, det.W_in, det.W, det.W_out,
                    [eg.leak_rate, eg.running_frames]])

    header = f"""// Generated by export_detector.py from {args.healthy}. Do not edit by hand:
// re-run export_detector.py to retrain, then re-upload the firmware.
#pragma once
#include <stdint.h>

#define DET_N_IN            {n_in}        // feature bands per frame
#define DET_N_RES           {n_res}       // reservoir neurons
#define DET_N_EXT           {n_ext}       // 1 + bands + neurons
#define DET_W_NNZ           {len(vals)}      // non-zero recurrent weights
#define DET_LEAK            {f32(eg.leak_rate)}
#define DET_RUNNING_FRAMES  {eg.running_frames}
#define DET_WASHOUT         {eg.washout}         // frames to ignore after a restart
#define DET_THRESHOLD       {f32(det.thresh)}
#define DET_MODEL_ID        0x{mid:08X}UL

// per-band normalization learned from the healthy recording
{c_array("float", "DET_MU", det.mu, f32)}
{c_array("float", "DET_SIG", det.sig, f32)}
// input weights: row i (neuron i) starts at DET_W_IN[i * DET_N_IN]
{c_array("float", "DET_W_IN", det.W_in.ravel(), f32)}
// sparse recurrent weights (see export_detector.py for the layout)
{c_array("uint16_t", "DET_W_ROW", row_start, str, 12)}
typedef {col_type} det_col_t;   // big enough to hold a neuron number
{c_array("det_col_t", "DET_W_COL", cols, str, 16)}
{c_array("float", "DET_W_VAL", vals, f32)}
// readout: band j's weights start at DET_W_OUT_T[j * DET_N_EXT]
{c_array("float", "DET_W_OUT_T", w_out_t.ravel(), f32)}
"""
    os.makedirs(FW_DIR, exist_ok=True)
    with open(os.path.join(FW_DIR, "detector_weights.h"), "w") as f:
        f.write(header)

    np.savez(os.path.join(FW_DIR, "detector_model.npz"),
             mu=det.mu, sig=det.sig, W_in=det.W_in, W=det.W, W_out=det.W_out,
             thresh=det.thresh, model_id=mid, healthy=args.healthy,
             leak_rate=eg.leak_rate, running_frames=eg.running_frames,
             reservoir_size=eg.reservoir_size)

    export_mel.OUT = os.path.join(FW_DIR, "mel_filters.h")
    export_mel.main()

    flash_kb = 4 * (det.W_in.size + len(vals) + w_out_t.size + 2 * n_in) / 1024 \
        + (len(cols) * (1 if n_res <= 256 else 2) + 2 * len(row_start)) / 1024
    base = det.cal_err[eg.washout:]
    print(f"wrote {os.path.join(FW_DIR, 'detector_weights.h')}")
    print(f"  model id        : 0x{mid:08X}")
    print(f"  reservoir       : {n_res} neurons, {len(vals)} non-zero recurrent weights "
          f"({100 * len(vals) / n_res ** 2:.0f}% of {n_res}x{n_res})")
    print(f"  size on the chip: {flash_kb:.0f} KB")
    print(f"  healthy score   : mean {base.mean():.3f}, threshold {det.thresh:.3f}")


if __name__ == "__main__":
    main()
